# Vivado-generated constraints (ChipScope, etc.)











connect_debug_port u_ila_0/probe0 [get_nets [list {inputCoupling_i/inputCouple[0].outData[0]} {inputCoupling_i/inputCouple[0].outData[1]} {inputCoupling_i/inputCouple[0].outData[2]} {inputCoupling_i/inputCouple[0].outData[3]} {inputCoupling_i/inputCouple[0].outData[4]} {inputCoupling_i/inputCouple[0].outData[5]} {inputCoupling_i/inputCouple[0].outData[6]} {inputCoupling_i/inputCouple[0].outData[7]} {inputCoupling_i/inputCouple[0].outData[8]} {inputCoupling_i/inputCouple[0].outData[9]} {inputCoupling_i/inputCouple[0].outData[10]} {inputCoupling_i/inputCouple[0].outData[11]} {inputCoupling_i/inputCouple[0].outData[12]} {inputCoupling_i/inputCouple[0].outData[13]} {inputCoupling_i/inputCouple[0].outData[14]} {inputCoupling_i/inputCouple[0].outData[15]} {inputCoupling_i/inputCouple[0].outData[16]} {inputCoupling_i/inputCouple[0].outData[17]} {inputCoupling_i/inputCouple[0].outData[18]} {inputCoupling_i/inputCouple[0].outData[19]} {inputCoupling_i/inputCouple[0].outData[20]} {inputCoupling_i/inputCouple[0].outData[21]} {inputCoupling_i/inputCouple[0].outData[22]} {inputCoupling_i/inputCouple[0].outData[23]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {inputCoupling_i/inputCouple[0].acData[0]} {inputCoupling_i/inputCouple[0].acData[1]} {inputCoupling_i/inputCouple[0].acData[2]} {inputCoupling_i/inputCouple[0].acData[3]} {inputCoupling_i/inputCouple[0].acData[4]} {inputCoupling_i/inputCouple[0].acData[5]} {inputCoupling_i/inputCouple[0].acData[6]} {inputCoupling_i/inputCouple[0].acData[7]} {inputCoupling_i/inputCouple[0].acData[8]} {inputCoupling_i/inputCouple[0].acData[9]} {inputCoupling_i/inputCouple[0].acData[10]} {inputCoupling_i/inputCouple[0].acData[11]} {inputCoupling_i/inputCouple[0].acData[12]} {inputCoupling_i/inputCouple[0].acData[13]} {inputCoupling_i/inputCouple[0].acData[14]} {inputCoupling_i/inputCouple[0].acData[15]} {inputCoupling_i/inputCouple[0].acData[16]} {inputCoupling_i/inputCouple[0].acData[17]} {inputCoupling_i/inputCouple[0].acData[18]} {inputCoupling_i/inputCouple[0].acData[19]} {inputCoupling_i/inputCouple[0].acData[20]} {inputCoupling_i/inputCouple[0].acData[21]} {inputCoupling_i/inputCouple[0].acData[22]} {inputCoupling_i/inputCouple[0].acData[23]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {inputCoupling_i/inputCouple[0].dcData[0]} {inputCoupling_i/inputCouple[0].dcData[1]} {inputCoupling_i/inputCouple[0].dcData[2]} {inputCoupling_i/inputCouple[0].dcData[3]} {inputCoupling_i/inputCouple[0].dcData[4]} {inputCoupling_i/inputCouple[0].dcData[5]} {inputCoupling_i/inputCouple[0].dcData[6]} {inputCoupling_i/inputCouple[0].dcData[7]} {inputCoupling_i/inputCouple[0].dcData[8]} {inputCoupling_i/inputCouple[0].dcData[9]} {inputCoupling_i/inputCouple[0].dcData[10]} {inputCoupling_i/inputCouple[0].dcData[11]} {inputCoupling_i/inputCouple[0].dcData[12]} {inputCoupling_i/inputCouple[0].dcData[13]} {inputCoupling_i/inputCouple[0].dcData[14]} {inputCoupling_i/inputCouple[0].dcData[15]} {inputCoupling_i/inputCouple[0].dcData[16]} {inputCoupling_i/inputCouple[0].dcData[17]} {inputCoupling_i/inputCouple[0].dcData[18]} {inputCoupling_i/inputCouple[0].dcData[19]} {inputCoupling_i/inputCouple[0].dcData[20]} {inputCoupling_i/inputCouple[0].dcData[21]} {inputCoupling_i/inputCouple[0].dcData[22]} {inputCoupling_i/inputCouple[0].dcData[23]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {inputCoupling_i/inputCouple[1].dcData[0]} {inputCoupling_i/inputCouple[1].dcData[1]} {inputCoupling_i/inputCouple[1].dcData[2]} {inputCoupling_i/inputCouple[1].dcData[3]} {inputCoupling_i/inputCouple[1].dcData[4]} {inputCoupling_i/inputCouple[1].dcData[5]} {inputCoupling_i/inputCouple[1].dcData[6]} {inputCoupling_i/inputCouple[1].dcData[7]} {inputCoupling_i/inputCouple[1].dcData[8]} {inputCoupling_i/inputCouple[1].dcData[9]} {inputCoupling_i/inputCouple[1].dcData[10]} {inputCoupling_i/inputCouple[1].dcData[11]} {inputCoupling_i/inputCouple[1].dcData[12]} {inputCoupling_i/inputCouple[1].dcData[13]} {inputCoupling_i/inputCouple[1].dcData[14]} {inputCoupling_i/inputCouple[1].dcData[15]} {inputCoupling_i/inputCouple[1].dcData[16]} {inputCoupling_i/inputCouple[1].dcData[17]} {inputCoupling_i/inputCouple[1].dcData[18]} {inputCoupling_i/inputCouple[1].dcData[19]} {inputCoupling_i/inputCouple[1].dcData[20]} {inputCoupling_i/inputCouple[1].dcData[21]} {inputCoupling_i/inputCouple[1].dcData[22]} {inputCoupling_i/inputCouple[1].dcData[23]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {inputCoupling_i/inputCouple[1].acData[0]} {inputCoupling_i/inputCouple[1].acData[1]} {inputCoupling_i/inputCouple[1].acData[2]} {inputCoupling_i/inputCouple[1].acData[3]} {inputCoupling_i/inputCouple[1].acData[4]} {inputCoupling_i/inputCouple[1].acData[5]} {inputCoupling_i/inputCouple[1].acData[6]} {inputCoupling_i/inputCouple[1].acData[7]} {inputCoupling_i/inputCouple[1].acData[8]} {inputCoupling_i/inputCouple[1].acData[9]} {inputCoupling_i/inputCouple[1].acData[10]} {inputCoupling_i/inputCouple[1].acData[11]} {inputCoupling_i/inputCouple[1].acData[12]} {inputCoupling_i/inputCouple[1].acData[13]} {inputCoupling_i/inputCouple[1].acData[14]} {inputCoupling_i/inputCouple[1].acData[15]} {inputCoupling_i/inputCouple[1].acData[16]} {inputCoupling_i/inputCouple[1].acData[17]} {inputCoupling_i/inputCouple[1].acData[18]} {inputCoupling_i/inputCouple[1].acData[19]} {inputCoupling_i/inputCouple[1].acData[20]} {inputCoupling_i/inputCouple[1].acData[21]} {inputCoupling_i/inputCouple[1].acData[22]} {inputCoupling_i/inputCouple[1].acData[23]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {inputCoupling_i/inputCouple[1].inData[0]} {inputCoupling_i/inputCouple[1].inData[1]} {inputCoupling_i/inputCouple[1].inData[2]} {inputCoupling_i/inputCouple[1].inData[3]} {inputCoupling_i/inputCouple[1].inData[4]} {inputCoupling_i/inputCouple[1].inData[5]} {inputCoupling_i/inputCouple[1].inData[6]} {inputCoupling_i/inputCouple[1].inData[7]} {inputCoupling_i/inputCouple[1].inData[8]} {inputCoupling_i/inputCouple[1].inData[9]} {inputCoupling_i/inputCouple[1].inData[10]} {inputCoupling_i/inputCouple[1].inData[11]} {inputCoupling_i/inputCouple[1].inData[12]} {inputCoupling_i/inputCouple[1].inData[13]} {inputCoupling_i/inputCouple[1].inData[14]} {inputCoupling_i/inputCouple[1].inData[15]} {inputCoupling_i/inputCouple[1].inData[16]} {inputCoupling_i/inputCouple[1].inData[17]} {inputCoupling_i/inputCouple[1].inData[18]} {inputCoupling_i/inputCouple[1].inData[19]} {inputCoupling_i/inputCouple[1].inData[20]} {inputCoupling_i/inputCouple[1].inData[21]} {inputCoupling_i/inputCouple[1].inData[22]} {inputCoupling_i/inputCouple[1].inData[23]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {inputCoupling_i/inputCouple[0].inData[0]} {inputCoupling_i/inputCouple[0].inData[1]} {inputCoupling_i/inputCouple[0].inData[2]} {inputCoupling_i/inputCouple[0].inData[3]} {inputCoupling_i/inputCouple[0].inData[4]} {inputCoupling_i/inputCouple[0].inData[5]} {inputCoupling_i/inputCouple[0].inData[6]} {inputCoupling_i/inputCouple[0].inData[7]} {inputCoupling_i/inputCouple[0].inData[8]} {inputCoupling_i/inputCouple[0].inData[9]} {inputCoupling_i/inputCouple[0].inData[10]} {inputCoupling_i/inputCouple[0].inData[11]} {inputCoupling_i/inputCouple[0].inData[12]} {inputCoupling_i/inputCouple[0].inData[13]} {inputCoupling_i/inputCouple[0].inData[14]} {inputCoupling_i/inputCouple[0].inData[15]} {inputCoupling_i/inputCouple[0].inData[16]} {inputCoupling_i/inputCouple[0].inData[17]} {inputCoupling_i/inputCouple[0].inData[18]} {inputCoupling_i/inputCouple[0].inData[19]} {inputCoupling_i/inputCouple[0].inData[20]} {inputCoupling_i/inputCouple[0].inData[21]} {inputCoupling_i/inputCouple[0].inData[22]} {inputCoupling_i/inputCouple[0].inData[23]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {inputCoupling_i/inputCouple[1].outData[0]} {inputCoupling_i/inputCouple[1].outData[1]} {inputCoupling_i/inputCouple[1].outData[2]} {inputCoupling_i/inputCouple[1].outData[3]} {inputCoupling_i/inputCouple[1].outData[4]} {inputCoupling_i/inputCouple[1].outData[5]} {inputCoupling_i/inputCouple[1].outData[6]} {inputCoupling_i/inputCouple[1].outData[7]} {inputCoupling_i/inputCouple[1].outData[8]} {inputCoupling_i/inputCouple[1].outData[9]} {inputCoupling_i/inputCouple[1].outData[10]} {inputCoupling_i/inputCouple[1].outData[11]} {inputCoupling_i/inputCouple[1].outData[12]} {inputCoupling_i/inputCouple[1].outData[13]} {inputCoupling_i/inputCouple[1].outData[14]} {inputCoupling_i/inputCouple[1].outData[15]} {inputCoupling_i/inputCouple[1].outData[16]} {inputCoupling_i/inputCouple[1].outData[17]} {inputCoupling_i/inputCouple[1].outData[18]} {inputCoupling_i/inputCouple[1].outData[19]} {inputCoupling_i/inputCouple[1].outData[20]} {inputCoupling_i/inputCouple[1].outData[21]} {inputCoupling_i/inputCouple[1].outData[22]} {inputCoupling_i/inputCouple[1].outData[23]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {inputCoupling_i/inputCouple[0].dataValid}]]
connect_debug_port u_ila_0/probe12 [get_nets [list {inputCoupling_i/inputCouple[0].outValid}]]
connect_debug_port u_ila_0/probe13 [get_nets [list {inputCoupling_i/inputCouple[1].dataValid}]]
connect_debug_port u_ila_0/probe14 [get_nets [list {inputCoupling_i/inputCouple[1].outValid}]]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list acqClk_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 24 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {inputCoupling_i/inputCoupler[0].outData[0]} {inputCoupling_i/inputCoupler[0].outData[1]} {inputCoupling_i/inputCoupler[0].outData[2]} {inputCoupling_i/inputCoupler[0].outData[3]} {inputCoupling_i/inputCoupler[0].outData[4]} {inputCoupling_i/inputCoupler[0].outData[5]} {inputCoupling_i/inputCoupler[0].outData[6]} {inputCoupling_i/inputCoupler[0].outData[7]} {inputCoupling_i/inputCoupler[0].outData[8]} {inputCoupling_i/inputCoupler[0].outData[9]} {inputCoupling_i/inputCoupler[0].outData[10]} {inputCoupling_i/inputCoupler[0].outData[11]} {inputCoupling_i/inputCoupler[0].outData[12]} {inputCoupling_i/inputCoupler[0].outData[13]} {inputCoupling_i/inputCoupler[0].outData[14]} {inputCoupling_i/inputCoupler[0].outData[15]} {inputCoupling_i/inputCoupler[0].outData[16]} {inputCoupling_i/inputCoupler[0].outData[17]} {inputCoupling_i/inputCoupler[0].outData[18]} {inputCoupling_i/inputCoupler[0].outData[19]} {inputCoupling_i/inputCoupler[0].outData[20]} {inputCoupling_i/inputCoupler[0].outData[21]} {inputCoupling_i/inputCoupler[0].outData[22]} {inputCoupling_i/inputCoupler[0].outData[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 24 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {inputCoupling_i/inputCoupler[0].inData[0]} {inputCoupling_i/inputCoupler[0].inData[1]} {inputCoupling_i/inputCoupler[0].inData[2]} {inputCoupling_i/inputCoupler[0].inData[3]} {inputCoupling_i/inputCoupler[0].inData[4]} {inputCoupling_i/inputCoupler[0].inData[5]} {inputCoupling_i/inputCoupler[0].inData[6]} {inputCoupling_i/inputCoupler[0].inData[7]} {inputCoupling_i/inputCoupler[0].inData[8]} {inputCoupling_i/inputCoupler[0].inData[9]} {inputCoupling_i/inputCoupler[0].inData[10]} {inputCoupling_i/inputCoupler[0].inData[11]} {inputCoupling_i/inputCoupler[0].inData[12]} {inputCoupling_i/inputCoupler[0].inData[13]} {inputCoupling_i/inputCoupler[0].inData[14]} {inputCoupling_i/inputCoupler[0].inData[15]} {inputCoupling_i/inputCoupler[0].inData[16]} {inputCoupling_i/inputCoupler[0].inData[17]} {inputCoupling_i/inputCoupler[0].inData[18]} {inputCoupling_i/inputCoupler[0].inData[19]} {inputCoupling_i/inputCoupler[0].inData[20]} {inputCoupling_i/inputCoupler[0].inData[21]} {inputCoupling_i/inputCoupler[0].inData[22]} {inputCoupling_i/inputCoupler[0].inData[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {inputCoupling_i/dcCoupled[0]} {inputCoupling_i/dcCoupled[1]} {inputCoupling_i/dcCoupled[2]} {inputCoupling_i/dcCoupled[3]} {inputCoupling_i/dcCoupled[4]} {inputCoupling_i/dcCoupled[5]} {inputCoupling_i/dcCoupled[6]} {inputCoupling_i/dcCoupled[7]} {inputCoupling_i/dcCoupled[8]} {inputCoupling_i/dcCoupled[9]} {inputCoupling_i/dcCoupled[10]} {inputCoupling_i/dcCoupled[11]} {inputCoupling_i/dcCoupled[12]} {inputCoupling_i/dcCoupled[13]} {inputCoupling_i/dcCoupled[14]} {inputCoupling_i/dcCoupled[15]} {inputCoupling_i/dcCoupled[16]} {inputCoupling_i/dcCoupled[17]} {inputCoupling_i/dcCoupled[18]} {inputCoupling_i/dcCoupled[19]} {inputCoupling_i/dcCoupled[20]} {inputCoupling_i/dcCoupled[21]} {inputCoupling_i/dcCoupled[22]} {inputCoupling_i/dcCoupled[23]} {inputCoupling_i/dcCoupled[24]} {inputCoupling_i/dcCoupled[25]} {inputCoupling_i/dcCoupled[26]} {inputCoupling_i/dcCoupled[27]} {inputCoupling_i/dcCoupled[28]} {inputCoupling_i/dcCoupled[29]} {inputCoupling_i/dcCoupled[30]} {inputCoupling_i/dcCoupled[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 24 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {inputCoupling_i/inputCoupler[0].acData[0]} {inputCoupling_i/inputCoupler[0].acData[1]} {inputCoupling_i/inputCoupler[0].acData[2]} {inputCoupling_i/inputCoupler[0].acData[3]} {inputCoupling_i/inputCoupler[0].acData[4]} {inputCoupling_i/inputCoupler[0].acData[5]} {inputCoupling_i/inputCoupler[0].acData[6]} {inputCoupling_i/inputCoupler[0].acData[7]} {inputCoupling_i/inputCoupler[0].acData[8]} {inputCoupling_i/inputCoupler[0].acData[9]} {inputCoupling_i/inputCoupler[0].acData[10]} {inputCoupling_i/inputCoupler[0].acData[11]} {inputCoupling_i/inputCoupler[0].acData[12]} {inputCoupling_i/inputCoupler[0].acData[13]} {inputCoupling_i/inputCoupler[0].acData[14]} {inputCoupling_i/inputCoupler[0].acData[15]} {inputCoupling_i/inputCoupler[0].acData[16]} {inputCoupling_i/inputCoupler[0].acData[17]} {inputCoupling_i/inputCoupler[0].acData[18]} {inputCoupling_i/inputCoupler[0].acData[19]} {inputCoupling_i/inputCoupler[0].acData[20]} {inputCoupling_i/inputCoupler[0].acData[21]} {inputCoupling_i/inputCoupler[0].acData[22]} {inputCoupling_i/inputCoupler[0].acData[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 24 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {inputCoupling_i/inputCoupler[0].dcData[0]} {inputCoupling_i/inputCoupler[0].dcData[1]} {inputCoupling_i/inputCoupler[0].dcData[2]} {inputCoupling_i/inputCoupler[0].dcData[3]} {inputCoupling_i/inputCoupler[0].dcData[4]} {inputCoupling_i/inputCoupler[0].dcData[5]} {inputCoupling_i/inputCoupler[0].dcData[6]} {inputCoupling_i/inputCoupler[0].dcData[7]} {inputCoupling_i/inputCoupler[0].dcData[8]} {inputCoupling_i/inputCoupler[0].dcData[9]} {inputCoupling_i/inputCoupler[0].dcData[10]} {inputCoupling_i/inputCoupler[0].dcData[11]} {inputCoupling_i/inputCoupler[0].dcData[12]} {inputCoupling_i/inputCoupler[0].dcData[13]} {inputCoupling_i/inputCoupler[0].dcData[14]} {inputCoupling_i/inputCoupler[0].dcData[15]} {inputCoupling_i/inputCoupler[0].dcData[16]} {inputCoupling_i/inputCoupler[0].dcData[17]} {inputCoupling_i/inputCoupler[0].dcData[18]} {inputCoupling_i/inputCoupler[0].dcData[19]} {inputCoupling_i/inputCoupler[0].dcData[20]} {inputCoupling_i/inputCoupler[0].dcData[21]} {inputCoupling_i/inputCoupler[0].dcData[22]} {inputCoupling_i/inputCoupler[0].dcData[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 24 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {inputCoupling_i/inputCoupler[1].inData[0]} {inputCoupling_i/inputCoupler[1].inData[1]} {inputCoupling_i/inputCoupler[1].inData[2]} {inputCoupling_i/inputCoupler[1].inData[3]} {inputCoupling_i/inputCoupler[1].inData[4]} {inputCoupling_i/inputCoupler[1].inData[5]} {inputCoupling_i/inputCoupler[1].inData[6]} {inputCoupling_i/inputCoupler[1].inData[7]} {inputCoupling_i/inputCoupler[1].inData[8]} {inputCoupling_i/inputCoupler[1].inData[9]} {inputCoupling_i/inputCoupler[1].inData[10]} {inputCoupling_i/inputCoupler[1].inData[11]} {inputCoupling_i/inputCoupler[1].inData[12]} {inputCoupling_i/inputCoupler[1].inData[13]} {inputCoupling_i/inputCoupler[1].inData[14]} {inputCoupling_i/inputCoupler[1].inData[15]} {inputCoupling_i/inputCoupler[1].inData[16]} {inputCoupling_i/inputCoupler[1].inData[17]} {inputCoupling_i/inputCoupler[1].inData[18]} {inputCoupling_i/inputCoupler[1].inData[19]} {inputCoupling_i/inputCoupler[1].inData[20]} {inputCoupling_i/inputCoupler[1].inData[21]} {inputCoupling_i/inputCoupler[1].inData[22]} {inputCoupling_i/inputCoupler[1].inData[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 24 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {inputCoupling_i/inputCoupler[1].outData[0]} {inputCoupling_i/inputCoupler[1].outData[1]} {inputCoupling_i/inputCoupler[1].outData[2]} {inputCoupling_i/inputCoupler[1].outData[3]} {inputCoupling_i/inputCoupler[1].outData[4]} {inputCoupling_i/inputCoupler[1].outData[5]} {inputCoupling_i/inputCoupler[1].outData[6]} {inputCoupling_i/inputCoupler[1].outData[7]} {inputCoupling_i/inputCoupler[1].outData[8]} {inputCoupling_i/inputCoupler[1].outData[9]} {inputCoupling_i/inputCoupler[1].outData[10]} {inputCoupling_i/inputCoupler[1].outData[11]} {inputCoupling_i/inputCoupler[1].outData[12]} {inputCoupling_i/inputCoupler[1].outData[13]} {inputCoupling_i/inputCoupler[1].outData[14]} {inputCoupling_i/inputCoupler[1].outData[15]} {inputCoupling_i/inputCoupler[1].outData[16]} {inputCoupling_i/inputCoupler[1].outData[17]} {inputCoupling_i/inputCoupler[1].outData[18]} {inputCoupling_i/inputCoupler[1].outData[19]} {inputCoupling_i/inputCoupler[1].outData[20]} {inputCoupling_i/inputCoupler[1].outData[21]} {inputCoupling_i/inputCoupler[1].outData[22]} {inputCoupling_i/inputCoupler[1].outData[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 24 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {inputCoupling_i/inputCoupler[1].dcData[0]} {inputCoupling_i/inputCoupler[1].dcData[1]} {inputCoupling_i/inputCoupler[1].dcData[2]} {inputCoupling_i/inputCoupler[1].dcData[3]} {inputCoupling_i/inputCoupler[1].dcData[4]} {inputCoupling_i/inputCoupler[1].dcData[5]} {inputCoupling_i/inputCoupler[1].dcData[6]} {inputCoupling_i/inputCoupler[1].dcData[7]} {inputCoupling_i/inputCoupler[1].dcData[8]} {inputCoupling_i/inputCoupler[1].dcData[9]} {inputCoupling_i/inputCoupler[1].dcData[10]} {inputCoupling_i/inputCoupler[1].dcData[11]} {inputCoupling_i/inputCoupler[1].dcData[12]} {inputCoupling_i/inputCoupler[1].dcData[13]} {inputCoupling_i/inputCoupler[1].dcData[14]} {inputCoupling_i/inputCoupler[1].dcData[15]} {inputCoupling_i/inputCoupler[1].dcData[16]} {inputCoupling_i/inputCoupler[1].dcData[17]} {inputCoupling_i/inputCoupler[1].dcData[18]} {inputCoupling_i/inputCoupler[1].dcData[19]} {inputCoupling_i/inputCoupler[1].dcData[20]} {inputCoupling_i/inputCoupler[1].dcData[21]} {inputCoupling_i/inputCoupler[1].dcData[22]} {inputCoupling_i/inputCoupler[1].dcData[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 24 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {inputCoupling_i/inputCoupler[1].acData[0]} {inputCoupling_i/inputCoupler[1].acData[1]} {inputCoupling_i/inputCoupler[1].acData[2]} {inputCoupling_i/inputCoupler[1].acData[3]} {inputCoupling_i/inputCoupler[1].acData[4]} {inputCoupling_i/inputCoupler[1].acData[5]} {inputCoupling_i/inputCoupler[1].acData[6]} {inputCoupling_i/inputCoupler[1].acData[7]} {inputCoupling_i/inputCoupler[1].acData[8]} {inputCoupling_i/inputCoupler[1].acData[9]} {inputCoupling_i/inputCoupler[1].acData[10]} {inputCoupling_i/inputCoupler[1].acData[11]} {inputCoupling_i/inputCoupler[1].acData[12]} {inputCoupling_i/inputCoupler[1].acData[13]} {inputCoupling_i/inputCoupler[1].acData[14]} {inputCoupling_i/inputCoupler[1].acData[15]} {inputCoupling_i/inputCoupler[1].acData[16]} {inputCoupling_i/inputCoupler[1].acData[17]} {inputCoupling_i/inputCoupler[1].acData[18]} {inputCoupling_i/inputCoupler[1].acData[19]} {inputCoupling_i/inputCoupler[1].acData[20]} {inputCoupling_i/inputCoupler[1].acData[21]} {inputCoupling_i/inputCoupler[1].acData[22]} {inputCoupling_i/inputCoupler[1].acData[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list evr/evrPPSmarker]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list evr/mgtWrapper_i/mgtLinkUp]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {inputCoupling_i/inputCoupler[0].acDataValid}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {inputCoupling_i/inputCoupler[1].acDataValid}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {inputCoupling_i/inputCoupler[0].outValid}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {inputCoupling_i/inputCoupler[1].outValid}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets acqClk_BUFG]
